create table if not exists monitor_state (
  id bigint generated by default as identity primary key,
  state_key text unique not null,
  state_value text not null,
  updated_at timestamp default now()
);
